name: Automate project assignments
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
      - name: add-new-issues-to-repository-based-project-column
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: takanabe/github-actions-automate-projects@v0.0.1
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/Dev-FE-1/projects/7
          GITHUB_PROJECT_COLUMN_NAME: Todo

      - name: add-new-prs-to-repository-based-project-column
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: takanabe/github-actions-automate-projects@v0.0.1
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/Dev-FE-1/projects/7
          GITHUB_PROJECT_COLUMN_NAME: In Progress
